#ifndef CCHAT_UTILS_H
#define CCHAT_UTILS_H

#define CCHAT_CTRL(x) ((x) & 0x1f)

#define CCHAT_CONNECTED_MSG "CCHAT_CONNECTED"
#define CCHAT_DISCONNECT_MSG "CCHAT_DISCONNECTED"
#define CCHAT_INVALID_MSG "RECIEVED AN INVALID MESSAGE!"

#endif
